### ISSUE TITLE
TWIG Task not rendering/parsing pages to ./dist

### ISSUE THREAD

**Issue by dirkbuslei** [GioLogist/Water#1]
The twig task uses the subfolders in ./src/pages and puts them in ./dist

for example : ./src/pages/index/index.twig ist delivered to ./dist/index/index.html

this is a problem as this page doesn't have the correct path to the assets as it is one folder to deep.

either the pages should not have subfolders or the twig task should deliver the renderd pages dirctly to ./dist, so that the path to the assets are correct and the dev server shows something.

**Comment by dirkbuslei** [comment]
oh i just saw your hack 'copy-home' task
but i found a better way to achive this i think, using gulp-rename to get rid of the folder names

`// Compile Twig Templates`
`gulp.task('twig', function () {`
`    return gulp.src('./src/pages/**/*.twig')`
`        .pipe(plugins.twigUpToDate())`
`        .pipe(plugins.rename({dirname: ''}))`
`        .pipe(gulp.dest('./dist/'))`
`        .pipe(plugins.browserSync.stream());`
`});`

**Comment by GioLogist** [comment]
Great idea and great implementation, tested and merged! 🤘🏼
